table:
  name: ChangeConfigurations
  schema: public
object_relationships:
  - name: Tenant
    using:
      foreign_key_constraint_on: tenantId
select_permissions:
  - role: user
    permission:
      columns:
        - readonly
        - key
        - stationId
        - value
        - id
        - tenantId
        - createdAt
        - updatedAt
      filter:
        tenantId:
          _eq: x-hasura-tenant-id
      allow_aggregations: true
    comment: ""
